# This file was generated by GoReleaser. DO NOT EDIT.
cask "agent-helper" do
  version "0.7.4"

  on_macos do
    on_intel do
      sha256 "e5f2aa379204cd3a69d8cb77a373892d76eb3c8e7444bcc8cf7ff9cd026785fa"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/agent-helper_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8d95757ce42ea912242d17aae80d5e8f540e181a15e953786952176bdacc7c01"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/agent-helper_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "891ac56aafaed2b50d7681c5a94ac4c13874cb07e45cd12004f612f25ab25150"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/agent-helper_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d7a8de163d8c6c816a7f17c4661de44b19aab4bcdd633b3712969c9e71d1f6a3"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/agent-helper_linux_arm64.tar.gz"
    end
  end

  name "agent-helper"
  desc "Unified AI coding agent dispatcher"
  homepage "https://github.com/vladzaharia/dotfiles-helpers"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agent-helper"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agent-helper"]
    system_command "/bin/ln", args: ["-sfn", "#{staged_path}/agent-helper", "#{HOMEBREW_PREFIX}/bin/ag"]
  end

  # No zap stanza required

  caveats <<~EOS
    Run `agent-helper setup` (or just `ag`) to configure on first use.
    The wizard walks you through agent selection, isolation mode,
    OrbStack/LM Studio integration, and credentials.
  EOS
end
