# This file was generated by GoReleaser. DO NOT EDIT.
cask "agent-helper" do
  binary "#{staged_path}/agent-helper", target: "ag"

  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "3d9d67d76ec52e6e36628b12f2e4bc1e4aae05810999a125d4c522b6db055252"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/agent-helper_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1362176da8a41bbb45feb7c09752ae0071c8e8a2d4d8d196f60ac973c8e8a0ff"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/agent-helper_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4f20f15837452138dea9ffb7971ef8068771787b1131cd995ba71f7f981614f1"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/agent-helper_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ef36042864a0942f45176620ea43e15f42dc7e59a6c1da3a9dc034dd82bde056"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/agent-helper_linux_arm64.tar.gz"
    end
  end

  name "agent-helper"
  desc "Unified AI coding agent dispatcher"
  homepage "https://github.com/vladzaharia/dotfiles-helpers"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agent-helper"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agent-helper"]
  end

  # No zap stanza required

end
