# This file was generated by GoReleaser. DO NOT EDIT.
cask "agent-helper" do
  version "0.7.2"

  on_macos do
    on_intel do
      sha256 "4f72c54259c4967f69c20d4eff9385fcf2552e4d3019f735fb3530e9483f6bf1"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/agent-helper_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "64904747854142b9636c4f1c2fc5f7218900c6f8d9ed65445b20533201bc7e94"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/agent-helper_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "314e88af3f454c19c73514ff5b01c3d851862aaf1fa37e99192a9a67ea5a2e6c"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/agent-helper_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5a3f3d9879a01d6801823d7ef042ad7b6c4da98b2ecc27385b83e558c768e07f"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/agent-helper_linux_arm64.tar.gz"
    end
  end

  name "agent-helper"
  desc "Unified AI coding agent dispatcher"
  homepage "https://github.com/vladzaharia/dotfiles-helpers"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agent-helper"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agent-helper"]
    system_command "/bin/ln", args: ["-sfn", "#{staged_path}/agent-helper", "#{HOMEBREW_PREFIX}/bin/ag"]
  end

  # No zap stanza required

  caveats <<~EOS
    Run `agent-helper setup` (or just `ag`) to configure on first use.
    The wizard walks you through agent selection, isolation mode,
    OrbStack/LM Studio integration, and credentials.
  EOS
end
