# This file was generated by GoReleaser. DO NOT EDIT.
cask "sops-helper" do
  version "0.7.1"

  on_macos do
    on_intel do
      sha256 "d23c802c817becac583fdc8bc9a7a14764458badc19476276ca14d9d08f5ba6e"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/sops-helper_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "41bc826b0a29e6f3c397f7f3a9dbfeaad16c63d677fa9e9939a63cd04e53a11c"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/sops-helper_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b901f1c531bd7a4171ac0d7f4b9b443241e2e8f12396fc6b9240588e07115402"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/sops-helper_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bfedcba5aee2524e8a8cd9e03092b579deee90fb745d7403bd98ab8311feab91"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/sops-helper_linux_arm64.tar.gz"
    end
  end

  name "sops-helper"
  desc "SOPS encryption/decryption CLI with glob support"
  homepage "https://github.com/vladzaharia/dotfiles-helpers"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sops-helper"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sops-helper"]
    system_command "/bin/ln", args: ["-sfn", "#{staged_path}/sops-helper", "#{HOMEBREW_PREFIX}/bin/crypto"]
  end

  # No zap stanza required

  caveats <<~EOS
    Alias installed: crypto. Run `crypto --help` to get started.
    Requires sops + at least one configured age key or KMS binding.
  EOS
end
