# This file was generated by GoReleaser. DO NOT EDIT.
cask "sops-helper" do
  version "0.6.2"

  on_macos do
    on_intel do
      sha256 "97d17fb5e5f1cd49ac5848aac1d1a9a423977776c3eba7b4cd1f0170bbfdbf78"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/sops-helper_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "093d3ed59cb135f07ea31c61a5a5f388824e302a10b6f5622445c1f4dd2cf4c6"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/sops-helper_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "73573332af7fb2e1aba6810a79d6c581473fac8960a512da66083f87b2d7531f"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/sops-helper_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ceb6e359c1de2f2bbd32c73568f8fde54c71eb6ff9576859d74265153fb07148"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/sops-helper_linux_arm64.tar.gz"
    end
  end

  name "sops-helper"
  desc "SOPS encryption/decryption CLI with glob support"
  homepage "https://github.com/vladzaharia/dotfiles-helpers"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sops-helper"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sops-helper"]
    system_command "/bin/ln", args: ["-sfn", "#{staged_path}/sops-helper", "#{HOMEBREW_PREFIX}/bin/crypto"]
  end

  # No zap stanza required

end
