# This file was generated by GoReleaser. DO NOT EDIT.
cask "sops-helper" do
  version "0.6.4"

  on_macos do
    on_intel do
      sha256 "decdc68bcc132e3269e2890ce22f36b4afcd47d67079cedf2df0851d6e49b658"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/sops-helper_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "321031a517b9cdc7c2f042c3b4641acfd07b87ca8098c1ee11b70c969cd8225d"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/sops-helper_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "682e7c2aba00f0174c7faf181b586516ced027ea8fa466bb0fb9277a2ef9cbd3"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/sops-helper_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b7132daefcef8f72eb738f1b99342d67c57819a32b1ba209c597e9ec946ee827"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/sops-helper_linux_arm64.tar.gz"
    end
  end

  name "sops-helper"
  desc "SOPS encryption/decryption CLI with glob support"
  homepage "https://github.com/vladzaharia/dotfiles-helpers"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sops-helper"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sops-helper"]
    system_command "/bin/ln", args: ["-sfn", "#{staged_path}/sops-helper", "#{HOMEBREW_PREFIX}/bin/crypto"]
  end

  # No zap stanza required

end
