# This file was generated by GoReleaser. DO NOT EDIT.
cask "vault-helper" do
  version "0.7.1"

  on_macos do
    on_intel do
      sha256 "7a5de1ffd1f0b69aa340d902391deb33a1e8a67da13aaf0b849838d5b8928c2a"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/vault-helper_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c8cd0a2223657a7cc01c6c8233a65803e6414d336b001057e0fc41599ea17430"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/vault-helper_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9add631f69dde4f0f6803c818fd995e99e95ea84fb40254faa3a4b7adf5cdf04"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/vault-helper_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ea99475cc9067bd7369a71a7ee4a31aa6293e3f1de67895aa50cc7e12afa84e4"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/vault-helper_linux_arm64.tar.gz"
    end
  end

  name "vault-helper"
  desc "HashiCorp Vault CLI helper (SSH certs, TOTP, env injection)"
  homepage "https://github.com/vladzaharia/dotfiles-helpers"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vault-helper"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vault-helper"]
    %w[vh vlogin vssh vmosh votp vtoken vnv vdocker].each do |a|
      system_command "/bin/ln", args: ["-sfn", "#{staged_path}/vault-helper", "#{HOMEBREW_PREFIX}/bin/#{a}"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Aliases installed: vh, vlogin, vssh, vmosh, votp, vtoken, vnv, vdocker.
    Run `vh --help` to get started. Configure VAULT_ADDR / VAULT_TOKEN
    in your shell rc to point at your Vault instance.
  EOS
end
