# This file was generated by GoReleaser. DO NOT EDIT.
cask "vault-helper" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "3f6ccc0235c1434229c55fabcc35caaa8177afaa81cdf0b3cf3e0cfcf914062b"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/vault-helper_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4ec3100612963411a1eb3095168bfe6138bcb774f3e1d703863278ceedd7eb34"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/vault-helper_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2f9240d6cea46fe562939afc9960cd07229b2827008157566c7bddd3745ff059"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/vault-helper_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d0e3e5f440ec6d12dde12decc2508ba9d5de67b724404c2c52ebec75c2232f56"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/vault-helper_linux_arm64.tar.gz"
    end
  end

  name "vault-helper"
  desc "HashiCorp Vault CLI helper (SSH certs, TOTP, env injection)"
  homepage "https://github.com/vladzaharia/dotfiles-helpers"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vault-helper"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vault-helper"]
    %w[vh vlogin vssh vmosh votp vtoken vnv vdocker].each do |a|
      system_command "/bin/ln", args: ["-sfn", "#{staged_path}/vault-helper", "#{HOMEBREW_PREFIX}/bin/#{a}"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Aliases installed: vh, vlogin, vssh, vmosh, votp, vtoken, vnv, vdocker.
    Run `vh --help` to get started. Configure VAULT_ADDR / VAULT_TOKEN
    in your shell rc to point at your Vault instance.
  EOS
end
