# This file was generated by GoReleaser. DO NOT EDIT.
cask "vault-helper" do
  version "0.6.5"

  on_macos do
    on_intel do
      sha256 "e223f7ca92a94cdafee2b55195d076d7d4654910932f640852d1cb1bb07dd040"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/vault-helper_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "23644832a5de23e48beab116c904a6156a9f79608affd738ce72bcef446d064f"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/vault-helper_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6bb4f3613aa681117c3033a96cce73750d973c54a84d6e2cddb51268e9f81cc0"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/vault-helper_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "46b4cafc0cfe4031f3c723002ee5f179f731988a69ef1fe007c05b1949118c7a"
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v#{version}/vault-helper_linux_arm64.tar.gz"
    end
  end

  name "vault-helper"
  desc "HashiCorp Vault CLI helper (SSH certs, TOTP, env injection)"
  homepage "https://github.com/vladzaharia/dotfiles-helpers"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vault-helper"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vault-helper"]
    %w[vh vlogin vssh vmosh votp vtoken vnv vdocker].each do |a|
      system_command "/bin/ln", args: ["-sfn", "#{staged_path}/vault-helper", "#{HOMEBREW_PREFIX}/bin/#{a}"]
    end
  end

  # No zap stanza required

end
