# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentHelper < Formula
  desc "Unified AI coding agent dispatcher"
  homepage "https://github.com/vladzaharia/dotfiles-helpers"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v0.5.0/agent-helper_darwin_amd64.tar.gz"
      sha256 "a7e54b966c29e920b342d34c828250c000400da4d2f4d8d6bc2b949e89cb8521"

      define_method(:install) do
        bin.install "agent-helper"
        bin.install_symlink "agent-helper" => "ag"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v0.5.0/agent-helper_darwin_arm64.tar.gz"
      sha256 "ef8e3c2e7a7779c785d05f99da96b7116247809013c6d5422ca4d2c809c7acd3"

      define_method(:install) do
        bin.install "agent-helper"
        bin.install_symlink "agent-helper" => "ag"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v0.5.0/agent-helper_linux_amd64.tar.gz"
      sha256 "22fd46d31c68cb370896af2f65b2dbce140b9dff7775fa854b5f8f1746bb324e"
      define_method(:install) do
        bin.install "agent-helper"
        bin.install_symlink "agent-helper" => "ag"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v0.5.0/agent-helper_linux_arm64.tar.gz"
      sha256 "fbaf02af277fddebf5d082b022fe99c6ebd8f39f057a277b2dda405800050e04"
      define_method(:install) do
        bin.install "agent-helper"
        bin.install_symlink "agent-helper" => "ag"
      end
    end
  end
end
