# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentHelper < Formula
  desc "Unified AI coding agent dispatcher"
  homepage "https://github.com/vladzaharia/dotfiles-helpers"
  version "0.5.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v0.5.2/agent-helper_darwin_amd64.tar.gz"
      sha256 "20a448031e1cf2adc6a2b4a3503fa82aa4bfed4381ae3f10124e53e845557b5c"

      define_method(:install) do
        bin.install "agent-helper"
        bin.install_symlink "agent-helper" => "ag"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v0.5.2/agent-helper_darwin_arm64.tar.gz"
      sha256 "4c83c37277b8c1cdad5c9afc7178f478b2a12f37b24174970fe114f89af7af3a"

      define_method(:install) do
        bin.install "agent-helper"
        bin.install_symlink "agent-helper" => "ag"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v0.5.2/agent-helper_linux_amd64.tar.gz"
      sha256 "85f537b010e070409c27c80a8bb24899ec09f479da0c4900db37369235d03562"
      define_method(:install) do
        bin.install "agent-helper"
        bin.install_symlink "agent-helper" => "ag"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v0.5.2/agent-helper_linux_arm64.tar.gz"
      sha256 "89ab8deb71c70968d1d6e3d59563e21fb5a6296385cb79e200f8d5299c005f86"
      define_method(:install) do
        bin.install "agent-helper"
        bin.install_symlink "agent-helper" => "ag"
      end
    end
  end
end
