# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentHelper < Formula
  desc "Unified AI coding agent dispatcher"
  homepage "https://github.com/vladzaharia/dotfiles-helpers"
  version "0.5.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v0.5.1/agent-helper_darwin_amd64.tar.gz"
      sha256 "b7f71999677dd8f3d621e177ea879064990d4d09813e71ce6fcfcf24f24de3fd"

      define_method(:install) do
        bin.install "agent-helper"
        bin.install_symlink "agent-helper" => "ag"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v0.5.1/agent-helper_darwin_arm64.tar.gz"
      sha256 "3102391aa45bb68523896534b1d87b49c0d0304e14e17de312dc731a0274afb9"

      define_method(:install) do
        bin.install "agent-helper"
        bin.install_symlink "agent-helper" => "ag"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v0.5.1/agent-helper_linux_amd64.tar.gz"
      sha256 "b466a3268a48f942a3c57cd84db6b1c6babbdfcb0cebe799ab7a3b32984735ea"
      define_method(:install) do
        bin.install "agent-helper"
        bin.install_symlink "agent-helper" => "ag"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v0.5.1/agent-helper_linux_arm64.tar.gz"
      sha256 "994fe035b89da4d479c8ad8f7945b39d256c20b8cfe4440398d82bab5f4494ec"
      define_method(:install) do
        bin.install "agent-helper"
        bin.install_symlink "agent-helper" => "ag"
      end
    end
  end
end
