# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SopsHelper < Formula
  desc "SOPS encryption/decryption CLI with glob support"
  homepage "https://github.com/vladzaharia/dotfiles-helpers"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v0.5.0/sops-helper_darwin_amd64.tar.gz"
      sha256 "e6494523592e233be732ddabc0eefe1d6b9cfd7d9c51b6fe441801d834a8e2bd"

      define_method(:install) do
        bin.install "sops-helper"
        bin.install_symlink "sops-helper" => "crypto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v0.5.0/sops-helper_darwin_arm64.tar.gz"
      sha256 "53e917f6a73800b97ba27dc588d38f710413a949eb7c31b053fe6f9866c866c2"

      define_method(:install) do
        bin.install "sops-helper"
        bin.install_symlink "sops-helper" => "crypto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v0.5.0/sops-helper_linux_amd64.tar.gz"
      sha256 "58f506060a33c362f051e47179e5f8f2a3d5ae578150361eff52e15f82e27ae7"
      define_method(:install) do
        bin.install "sops-helper"
        bin.install_symlink "sops-helper" => "crypto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v0.5.0/sops-helper_linux_arm64.tar.gz"
      sha256 "96b59133eb5829aba1a8db3d685cd5447794f118aac02b85b65f0beb7d402c81"
      define_method(:install) do
        bin.install "sops-helper"
        bin.install_symlink "sops-helper" => "crypto"
      end
    end
  end
end
