# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VaultHelper < Formula
  desc "HashiCorp Vault CLI helper (SSH certs, TOTP, env injection)"
  homepage "https://github.com/vladzaharia/dotfiles-helpers"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v0.5.0/vault-helper_darwin_amd64.tar.gz"
      sha256 "2beeabfcd81f654ee9b5b17a80038940173e67b0d5188389d7811964be563a8e"

      define_method(:install) do
        bin.install "vault-helper"
        %w[vh vlogin vssh vmosh votp vtoken vnv vdocker].each do |name|
          bin.install_symlink "vault-helper" => name
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v0.5.0/vault-helper_darwin_arm64.tar.gz"
      sha256 "aeeb9a3673125045ab69db35d9a24e860bc270e089146f5da3184032b651ba3d"

      define_method(:install) do
        bin.install "vault-helper"
        %w[vh vlogin vssh vmosh votp vtoken vnv vdocker].each do |name|
          bin.install_symlink "vault-helper" => name
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v0.5.0/vault-helper_linux_amd64.tar.gz"
      sha256 "d884879ca339616f6f1b678feb8aeeefcb34be7e02aff8b5ace89a64d0aabf9f"
      define_method(:install) do
        bin.install "vault-helper"
        %w[vh vlogin vssh vmosh votp vtoken vnv vdocker].each do |name|
          bin.install_symlink "vault-helper" => name
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v0.5.0/vault-helper_linux_arm64.tar.gz"
      sha256 "a40552746fb705d441074b5c43c0e2481fc642ae7ff57c1738c1812152f1588c"
      define_method(:install) do
        bin.install "vault-helper"
        %w[vh vlogin vssh vmosh votp vtoken vnv vdocker].each do |name|
          bin.install_symlink "vault-helper" => name
        end
      end
    end
  end
end
