# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VaultHelper < Formula
  desc "HashiCorp Vault CLI helper (SSH certs, TOTP, env injection)"
  homepage "https://github.com/vladzaharia/dotfiles-helpers"
  version "0.5.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v0.5.1/vault-helper_darwin_amd64.tar.gz"
      sha256 "d6bc14235e7a95c7ade9ea34e0b17caac2baffb424b3f8f615254fd582c17131"

      define_method(:install) do
        bin.install "vault-helper"
        %w[vh vlogin vssh vmosh votp vtoken vnv vdocker].each do |name|
          bin.install_symlink "vault-helper" => name
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v0.5.1/vault-helper_darwin_arm64.tar.gz"
      sha256 "c66c2f9ee7228fedbb7b99c5b5e4f5ffad798da001fc8a40feba4faf63d8edd3"

      define_method(:install) do
        bin.install "vault-helper"
        %w[vh vlogin vssh vmosh votp vtoken vnv vdocker].each do |name|
          bin.install_symlink "vault-helper" => name
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v0.5.1/vault-helper_linux_amd64.tar.gz"
      sha256 "d709c0777488b29555b4bbe21549874c5247c5850296ced1c5c784882fdd5d9b"
      define_method(:install) do
        bin.install "vault-helper"
        %w[vh vlogin vssh vmosh votp vtoken vnv vdocker].each do |name|
          bin.install_symlink "vault-helper" => name
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vladzaharia/dotfiles-helpers/releases/download/v0.5.1/vault-helper_linux_arm64.tar.gz"
      sha256 "208b819651f5242cb913d8e25338310967876147fac5ccd5fb7231c95b9f7e4b"
      define_method(:install) do
        bin.install "vault-helper"
        %w[vh vlogin vssh vmosh votp vtoken vnv vdocker].each do |name|
          bin.install_symlink "vault-helper" => name
        end
      end
    end
  end
end
